2025-12-23 22:00:54 0 [Note] Starting MariaDB 10.11.11-MariaDB source revision e69f8cae1a15e15b9e4f5e0f8497e1f17bdc81a4 server_uid CYb2lFZyQj/OEFuH0maDwV1dsuk= as process 13416
2025-12-23 22:00:54 0 [Note] InnoDB: Compressed tables use zlib 1.3.1
2025-12-23 22:00:54 0 [Note] InnoDB: Number of transaction pools: 1
2025-12-23 22:00:54 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2025-12-23 22:00:54 0 [Note] InnoDB: Using liburing
2025-12-23 22:00:54 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
2025-12-23 22:00:54 0 [Note] InnoDB: Initialized memory pressure event listener
2025-12-23 22:00:54 0 [Note] InnoDB: Completed initialization of buffer pool
2025-12-23 22:00:54 0 [Note] InnoDB: File system buffers for log disabled (block size=4096 bytes)
2025-12-23 22:00:54 0 [Note] InnoDB: End of log at LSN=36913
2025-12-23 22:00:54 0 [Note] InnoDB: 128 rollback segments are active.
2025-12-23 22:00:54 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
2025-12-23 22:00:54 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
2025-12-23 22:00:54 0 [Note] InnoDB: log sequence number 36913; transaction id 5
2025-12-23 22:00:54 0 [Note] Plugin 'FEEDBACK' is disabled.
2025-12-23 22:00:54 0 [Note] InnoDB: Loading buffer pool(s) from /home/jim/Dev/NGOL-D/data/mariadb/ib_buffer_pool
2025-12-23 22:00:54 0 [ERROR] mariadbd: unknown option '--initialize'
2025-12-23 22:00:54 0 [ERROR] mariadbd: unknown variable 'auth-root-authentication-method=normal'
2025-12-23 22:00:54 0 [ERROR] Aborting
